version: "3.9"
services:
  watermarker:
    build: .
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    env_file:
      - .env
    user: "${USER_ID:-0}:${GROUP_ID:-0}"
    volumes:
      - watermarker_output:/app/output
      - watermarker_uploads:/app/uploads

volumes:
  watermarker_output:
  watermarker_uploads:
