version: "3.9"
services:
  watermarker:
    build: .
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    env_file:
      - .env
    volumes:
      - ./output:/app/output
      - ./uploads:/app/uploads
